import Head from "next/head";
import Earnings from "@/components/Cards/Earning";
import Saave from "@/components/Cards/Saave";

export default function Home() {
  return (
    <>
      <Head>
        <title>SAAVE | Main</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="font-Inter">
        {/* <Earnings /> */}
        <Saave />
      </main>
    </>
  );
}
